# Generated by Django 5.2.16 on 2026-07-16 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('babies', '0001_initial'),
        ('bracelets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('spo2', models.FloatField(blank=True, null=True)),
                ('movement', models.JSONField(blank=True, null=True)),
                ('battery', models.FloatField(blank=True, null=True)),
                ('skin_contact', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='babies.baby')),
                ('bracelet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='bracelets.bracelet')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['baby', 'recorded_at'], name='meas_baby_recorded_idx')],
            },
        ),
    ]
