# Generated by Django 5.2.16 on 2026-07-16 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('babies', '0001_initial'),
        ('bracelets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='babies.baby'),
        ),
        migrations.AddField(
            model_name='alert',
            name='bracelet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='bracelets.bracelet'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['baby', 'triggered_at'], name='alert_baby_triggered_idx'),
        ),
    ]
