# Generated by Django 5.2.16 on 2026-08-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('alert', 'Alert'), ('bracelet', 'Bracelet'), ('medical', 'Medical'), ('system', 'System')], default='system', max_length=10),
        ),
    ]
