# Generated by Django 5.2.16 on 2026-07-16 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('babies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='baby',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babies', to='users.parent'),
        ),
        migrations.AddField(
            model_name='medicalhistoryentry',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='babies.baby'),
        ),
        migrations.AddField(
            model_name='medicalhistoryentry',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.doctor'),
        ),
        migrations.AddField(
            model_name='medicalhistoryentry',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='babies.medicalhistoryentry'),
        ),
    ]
