/// In-app BLE simulator (Section 22) — implements the same VitalsSource
/// interface as the real hardware (ble_service.dart), so every screen works
/// identically against either. Exists because the ESP32 hardware isn't
/// available project-wide yet; switching to real hardware later is a
/// one-line change in providers.dart's `bleServiceProvider`, not a rewrite
/// of any screen.
///
/// Scenario vocabulary intentionally matches
/// tools/simulator/bracelet_simulator.py (normal/fever/hypoxia/tachy/
/// lowbatt) so a dev reading the Python simulator's README already knows
/// what each simulated device here does.
import 'dart:async';
import 'dart:math';

import 'vitals_source.dart';

class SimulatorVitalsSource implements VitalsSource {
  final _statusCtrl = StreamController<BleStatus>.broadcast();
  final _vitalsCtrl = StreamController<LiveVitals>.broadcast();
  final Random _rand = Random();

  @override
  Stream<BleStatus> get status => _statusCtrl.stream;
  @override
  Stream<LiveVitals> get vitals => _vitalsCtrl.stream;

  Timer? _ticker;
  DateTime? _connectedSince;
  DateTime? _lastPacketAt;
  final List<DateTime> _recentPacketTimes = [];
  int _reconnectAttempt = 0;
  String _scenario = 'normal';

  @override
  String firmwareVersion = 'SIM-1.0.0';
  @override
  String deviceSerial = '';

  @override
  int get reconnectAttempts => _reconnectAttempt;
  @override
  DateTime? get connectedSince => _connectedSince;
  @override
  DateTime? get lastPacketAt => _lastPacketAt;

  @override
  int get packetsPerMinute {
    final cutoff = DateTime.now().subtract(const Duration(minutes: 1));
    _recentPacketTimes.removeWhere((t) => t.isBefore(cutoff));
    return _recentPacketTimes.length;
  }

  /// Fake device list — names encode which scenario connecting to them
  /// simulates, same idea as `--scenario` on the Python simulator.
  static const _fakeDevices = [
    DiscoveredDevice(id: 'SIM-NORMAL-0001', name: 'SB-SIMULATOR (normal)', rssi: -42),
    DiscoveredDevice(id: 'SIM-FEVER-0001', name: 'SB-SIMULATOR (fever demo)', rssi: -55),
    DiscoveredDevice(id: 'SIM-HYPOXIA-0001', name: 'SB-SIMULATOR (hypoxia demo)', rssi: -58),
    DiscoveredDevice(id: 'SIM-TACHY-0001', name: 'SB-SIMULATOR (tachycardia demo)', rssi: -50),
    DiscoveredDevice(id: 'SIM-LOWBATT-0001', name: 'SB-SIMULATOR (low battery demo)', rssi: -65),
  ];

  @override
  Future<List<DiscoveredDevice>> scan({Duration timeout = const Duration(seconds: 2)}) async {
    _statusCtrl.add(BleStatus.scanning);
    final wait = timeout > const Duration(seconds: 2) ? const Duration(seconds: 2) : timeout;
    await Future.delayed(wait);
    _statusCtrl.add(_ticker == null ? BleStatus.disconnected : BleStatus.connected);
    return _fakeDevices;
  }

  @override
  Future<void> connect(DiscoveredDevice device) async {
    _statusCtrl.add(BleStatus.connecting);
    await Future.delayed(const Duration(milliseconds: 400)); // feels like a real handshake
    deviceSerial = device.id;
    _scenario = switch (device.id) {
      'SIM-FEVER-0001' => 'fever',
      'SIM-HYPOXIA-0001' => 'hypoxia',
      'SIM-TACHY-0001' => 'tachy',
      'SIM-LOWBATT-0001' => 'lowbatt',
      _ => 'normal',
    };
    _connectedSince = DateTime.now();
    _reconnectAttempt = 0;
    _statusCtrl.add(BleStatus.connected);
    _startTicking();
  }

  void _startTicking() {
    _ticker?.cancel();
    // Matches the firmware's real cadence (uml.md: "loop every 5s").
    _ticker = Timer.periodic(const Duration(seconds: 5), (_) => _emitTick());
    _emitTick();
  }

  void _emitTick() {
    _lastPacketAt = DateTime.now();
    _recentPacketTimes.add(_lastPacketAt!);
    _vitalsCtrl.add(_generate());
  }

  double _jitter(double base, double spread) =>
      base + (_rand.nextDouble() * 2 - 1) * spread;

  Map<String, dynamic> _movement() => {
        'accel': [_jitter(0, 0.4), _jitter(0, 0.4), _jitter(9.8, 0.4)],
        'gyro': [_jitter(0, 3), _jitter(0, 3), _jitter(0, 3)],
        'magnitude': _jitter(1.0, 0.3),
      };

  LiveVitals _generate() {
    // Baselines mirror bracelet_simulator.py's scenarios so a reading here
    // means the same thing it means when generated by the Python script.
    final (hr, temp, spo2, battery) = switch (_scenario) {
      'fever' => (_jitter(150, 8), _jitter(38.6, 0.3), _jitter(97, 1), _jitter(70, 2)),
      'hypoxia' => (_jitter(140, 8), _jitter(36.9, 0.2), _jitter(88, 2), _jitter(70, 2)),
      'tachy' => (_jitter(195, 6), _jitter(37.0, 0.2), _jitter(97, 1), _jitter(70, 2)),
      'lowbatt' => (_jitter(130, 6), _jitter(36.9, 0.2), _jitter(98, 1), _jitter(8, 2)),
      _ => (_jitter(130, 6), _jitter(36.9, 0.2), _jitter(98, 1), _jitter(75, 2)),
    };
    return LiveVitals(
      heartRate: hr,
      temperature: temp,
      spo2: spo2,
      battery: battery,
      skinContact: true,
      movement: _movement(),
      timestamp: DateTime.now(),
    );
  }

  @override
  Future<void> sendCommand(String command) async {
    // The simulated device accepts any command instantly — nothing to wire
    // it to since there's no real firmware to rename/reset.
  }

  @override
  Future<void> disconnect() async {
    _ticker?.cancel();
    _ticker = null;
    _connectedSince = null;
    _recentPacketTimes.clear();
    _statusCtrl.add(BleStatus.disconnected);
  }

  @override
  Future<void> clearBond() => disconnect();

  @override
  void dispose() {
    _ticker?.cancel();
    _statusCtrl.close();
    _vitalsCtrl.close();
  }
}
