# Generated by Django 5.2.16 on 2026-07-16 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('babies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracelet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('firmware_version', models.CharField(blank=True, max_length=32)),
                ('battery_level', models.FloatField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='inactive', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracelets', to='babies.baby')),
            ],
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paired_at', models.DateTimeField(auto_now_add=True)),
                ('unpaired_at', models.DateTimeField(blank=True, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='babies.baby')),
                ('bracelet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='bracelets.bracelet')),
            ],
            options={
                'ordering': ['-paired_at'],
            },
        ),
    ]
